package com.mos.inventory.dto;

public enum EquipTransactionMessage {
    RESERVATION_ERROR,
    RENTAL_ERROR,
    USER_ERROR,
    EQUIPMENT_ID_LIST_ERROR,
    DATE_ERROR,
    INVALID_TRANSACTION_TYPE,
    SUCCESSFUL_RESERVATION,
    SUCCESSFUL_RENTAL,
    SUCCESSFUL_RETURN,
    INVALID_RENTAL_ID
}